from app.collectors.base import BaseCollector


class MockCollector(BaseCollector):
    def __init__(self, max_items: int = 10) -> None:
        self._max_items = max_items

    def collect(self) -> list[dict]:
        items = [
            {
                "external_id": "mock-notebook-001",
                "source": "mock",
                "title": "Notebook Gamer Acer Nitro 5 Intel Core i5 16GB 512GB SSD",
                "price": 4299.00,
                "final_price": 4299.00,
                "old_price": 5599.00,
                "category": "eletronicos",
                "store": "Mock Store",
                "seller_id": "seller-ele-001",
                "seller_name": "Tech Mock",
                "is_official_store": True,
                "free_shipping": True,
                "rating": 4.7,
                "sales": 320,
                "url": "https://example.com/notebook",
                "affiliate_url": "https://example.com/afiliado/notebook",
            },
            {
                "external_id": "mock-sofa-001",
                "source": "mock",
                "title": "Sofá Retrátil 3 Lugares Suede Cinza",
                "price": 1899.00,
                "final_price": 1899.00,
                "old_price": 2499.00,
                "category": "moveis",
                "store": "Mock Móveis",
                "seller_id": "seller-mov-001",
                "free_shipping": False,
                "url": "https://example.com/sofa",
            },
            {
                "external_id": "mock-airfryer-001",
                "source": "mock",
                "title": "Fritadeira Air Fryer 5L Digital",
                "price": 349.90,
                "final_price": 349.90,
                "old_price": 499.90,
                "category": "casa",
                "store": "Mock Casa",
                "seller_id": "seller-casa-001",
                "free_shipping": True,
                "url": "https://example.com/airfryer",
            },
            {
                "external_id": "mock-tenis-001",
                "source": "mock",
                "title": "Tênis Nike Revolution 6 Masculino",
                "price": 279.99,
                "final_price": 279.99,
                "old_price": 399.99,
                "category": "roupas",
                "store": "Mock Moda",
                "seller_id": "seller-roup-001",
                "url": "https://example.com/tenis",
            },
            {
                "external_id": "mock-perfume-001",
                "source": "mock",
                "title": "Perfume Importado Eau de Toilette 100ml",
                "price": 189.90,
                "final_price": 189.90,
                "old_price": 259.90,
                "category": "beleza",
                "store": "Mock Beleza",
                "seller_id": "seller-bel-001",
                "url": "https://example.com/perfume",
            },
            {
                "external_id": "mock-bike-001",
                "source": "mock",
                "title": "Bicicleta Ergométrica Spinning Profissional",
                "price": 1299.00,
                "final_price": 1299.00,
                "old_price": 1799.00,
                "category": "esportes",
                "store": "Mock Fitness",
                "seller_id": "seller-esp-001",
                "free_shipping": True,
                "url": "https://example.com/bike",
            },
            {
                "external_id": "mock-ps5-001",
                "source": "mock",
                "title": "Console Playstation 5 Slim Edição Digital 825 GB",
                "price": 3299.00,
                "final_price": 3299.00,
                "old_price": 3799.00,
                "category": "games",
                "store": "Mock Store",
                "seller_id": "seller-001",
                "seller_name": "Mock Oficial",
                "is_official_store": True,
                "free_shipping": True,
                "coupon_code": "ALLSITE7DO7",
                "payment_method": "pix",
                "requires_pix": True,
                "price_conditions": ["Cupom ALLSITE7DO7", "Pagamento via Pix"],
                "url": "https://example.com/ps5",
                "affiliate_url": "https://example.com/afiliado/ps5",
            },
            {
                "external_id": "mock-headphone-001a",
                "source": "mock",
                "title": "Headphone Bluetooth JBL Tune 510BT Preto",
                "price": 199.90,
                "final_price": 199.90,
                "old_price": 249.90,
                "canonical_product_id": "jbl-tune-510bt",
                "category": "eletronicos",
                "store": "Mock Store A",
                "seller_id": "seller-a",
                "seller_name": "Loja A",
                "is_official_store": False,
                "free_shipping": False,
                "url": "https://example.com/headphone-a",
            },
            {
                "external_id": "mock-headphone-001b",
                "source": "mock",
                "title": "Headphone Bluetooth JBL Tune 510BT Preto",
                "price": 199.90,
                "final_price": 199.90,
                "old_price": 249.90,
                "canonical_product_id": "jbl-tune-510bt",
                "category": "eletronicos",
                "store": "Mock Store B",
                "seller_id": "seller-b",
                "seller_name": "Loja B",
                "is_official_store": False,
                "free_shipping": False,
                "url": "https://example.com/headphone-b",
            },
            {
                "external_id": "mock-headphone-001c",
                "source": "mock",
                "title": "Headphone Bluetooth JBL Tune 510BT Preto Promoção",
                "price": 179.90,
                "final_price": 179.90,
                "old_price": 249.90,
                "canonical_product_id": "jbl-tune-510bt",
                "category": "eletronicos",
                "store": "Mock Store C",
                "seller_id": "seller-c",
                "seller_name": "Loja C",
                "is_official_store": True,
                "free_shipping": True,
                "rating": 4.8,
                "sales": 1500,
                "url": "https://example.com/headphone-c",
            },
            {
                "external_id": "mock-tv-001",
                "source": "mock",
                "title": "Smart TV 55 Polegadas 4K UHD",
                "price": 2499.00,
                "final_price": 2199.00,
                "old_price": 2499.00,
                "discount_percentage": 12.0,
                "category": "eletronicos",
                "store": "Mock Eletrônicos",
                "seller_id": "seller-tv-001",
                "is_official_store": True,
                "free_shipping": True,
                "url": "https://example.com/smart-tv",
                "affiliate_url": "https://example.com/afiliado/smart-tv",
            },
        ]
        return items[: self._max_items]
